whenever sqlerror exit sql.sqlcode

create table categories (
    category_id number generated by default as identity primary key,
    category_code varchar2(30 char) not null unique,
    category_name varchar2(100 char) not null,
    display_order number default 100 not null,
    is_active char(1 char) default 'Y' not null,
    created_at timestamp default systimestamp not null,
    constraint categories_active_ck check (is_active in ('Y', 'N'))
);

create table public_contents (
    content_id number generated by default as identity primary key,
    category_id number not null,
    title varchar2(200 char) not null,
    summary varchar2(500 char) not null,
    body clob not null,
    status varchar2(20 char) default 'DRAFT' not null,
    published_at timestamp not null,
    created_at timestamp default systimestamp not null,
    updated_at timestamp default systimestamp not null,
    constraint public_contents_category_fk
        foreign key (category_id) references categories (category_id),
    constraint public_contents_status_ck
        check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

create index public_contents_ix1
    on public_contents (status, published_at desc);

create index public_contents_ix2
    on public_contents (category_id, status);

commit;
